// <auto-generated />
using System;
using Lab2.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab2.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241030105611_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab2.DataAccess.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndingAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartingAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndingAt = new DateTime(1, 1, 1, 1, 30, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            StartingAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Topic = "why 2 + 2 != 4"
                        },
                        new
                        {
                            Id = 2,
                            EndingAt = new DateTime(2024, 10, 30, 14, 26, 11, 352, DateTimeKind.Local).AddTicks(4337),
                            InstructorId = 1,
                            StartingAt = new DateTime(2024, 10, 30, 12, 56, 11, 352, DateTimeKind.Local).AddTicks(4296),
                            Topic = "why 2 + 2 != 4"
                        },
                        new
                        {
                            Id = 3,
                            EndingAt = new DateTime(2024, 10, 31, 14, 56, 11, 352, DateTimeKind.Local).AddTicks(4342),
                            InstructorId = 1,
                            StartingAt = new DateTime(2024, 10, 31, 12, 56, 11, 352, DateTimeKind.Local).AddTicks(4339),
                            Topic = "Introduction to Quantum Mechanics"
                        },
                        new
                        {
                            Id = 4,
                            EndingAt = new DateTime(2024, 11, 1, 14, 26, 11, 352, DateTimeKind.Local).AddTicks(4346),
                            InstructorId = 1,
                            StartingAt = new DateTime(2024, 11, 1, 12, 56, 11, 352, DateTimeKind.Local).AddTicks(4344),
                            Topic = "Advanced Mathematics"
                        },
                        new
                        {
                            Id = 5,
                            EndingAt = new DateTime(2024, 11, 2, 14, 56, 11, 352, DateTimeKind.Local).AddTicks(4350),
                            InstructorId = 2,
                            StartingAt = new DateTime(2024, 11, 2, 12, 56, 11, 352, DateTimeKind.Local).AddTicks(4348),
                            Topic = "Philosophy of Science"
                        },
                        new
                        {
                            Id = 6,
                            EndingAt = new DateTime(2024, 11, 3, 14, 26, 11, 352, DateTimeKind.Local).AddTicks(4353),
                            InstructorId = 2,
                            StartingAt = new DateTime(2024, 11, 3, 12, 56, 11, 352, DateTimeKind.Local).AddTicks(4352),
                            Topic = "History of Art"
                        });
                });

            modelBuilder.Entity("Lab2.DataAccess.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JoinedOn = new DateOnly(2001, 7, 7),
                            Name = "Instruktors 1",
                            Surname = "aaaaaaaaaaa"
                        },
                        new
                        {
                            Id = 2,
                            JoinedOn = new DateOnly(2010, 12, 1),
                            Name = "Instruktors 2",
                            Surname = "bbbbbbbbbbbbbbb"
                        });
                });

            modelBuilder.Entity("Lab2.DataAccess.Course", b =>
                {
                    b.HasOne("Lab2.DataAccess.Instructor", null)
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab2.DataAccess.Instructor", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
